language: c
dist: trusty
before_install:
  - sudo apt-get install automake autoconf libtool libssl-dev sed make gawk sed bash dh-exec
script: ./bootstrap.sh && ./configure --with-openssl --prefix=/usr && make -j4 check
